name: testapp
version: 0.1.0
summary: A simple testing application
description: Some description

confinement: strict
base: core22
grade: stable
icon: ./snap/gui/com.example.testapp.png

slots:
  testapp: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: testapp_com.example.testapp # adjust accordingly to your app name and

apps:
  testapp:
    command: testapp
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
      - desktop
      - desktop-legacy
      - unity7
      - x11
      - wayland
    slots:
      - testapp
    common-id: com.example.testapp # adjust accordingly to your app name
    desktop: ./snap/gui/com.example.testapp.desktop # adjust accordingly to your app name

parts:
  testapp:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
